### ISSUE TITLE
codegangsta/cli is now urfave/cli

### ISSUE THREAD

**Issue by thebitguru** [olebedev/on#1]
Hi, @olebedev,

This no longer works because codegangsta/cli is now urfave/cli.  Are you accepting PRs?  If so, I can submit one.

Thanks!

**Comment by olebedev** [comment]
Hey @thebitguru, sure! PRs are very welcome :D

**Comment by thebitguru** [comment]
Great!  Thanks for the quick reply.  I just submitted #2.  I will go ahead and close this issue.
